version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: bun dev
    links:
      - frontend:frontend
      - db:db
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package.json

  db:
    image: "postgres"
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_volume:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgres_volume:
